# Complete pipeline configuration
pipeline:
  name: "Food Segmentation with Metadata"
  version: "1.0"
  
  stages:
    - name: "detection"
      enabled: true
      model: "yolov8m-seg"
      confidence_threshold: 0.5
      
    - name: "metadata_extraction"
      enabled: true
      models:
        - "food_classifier"
        - "cuisine_identifier"
        - "portion_estimator"
      
    - name: "output_generation"
      enabled: true
      formats: ["json", "csv", "report", "visualization"]

# Processing options
processing:
  batch_size: 8
  use_gpu: true
  num_workers: 4
  
# Output settings
output:
  save_crops: true
  save_masks: true
  save_visualization: true
  compression_quality: 90