augmentation:
  degrees: 15
  fliplr: 0.5
  flipud: 0.5
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  mixup: 0.2
  mosaic: 1.0
  scale: 0.5
  translate: 0.1
model:
  base_model: yolov8n.pt
  input_size: 640
optimization:
  box: 7.5
  cls: 0.5
  dfl: 1.5
  lr0: 0.001
  lrf: 0.01
  momentum: 0.937
  optimizer: AdamW
  warmup_epochs: 3.0
  weight_decay: 0.0005
training:
  batch: 8
  device: cpu
  epochs: 50
  name: food_detector_v1
  patience: 20
  project: food_training_runs
  workers: 2
